# Accessing/Changing removing a specific element,row, column, etc

In [1]:
import numpy as np

In [70]:
a = np.array([[12,3,3,2,3,5,3], [2,32,4,2,7,9,3]])
print(a)

[[12  3  3  2  3  5  3]
 [ 2 32  4  2  7  9  3]]


In [71]:
a.shape


(2, 7)

In [72]:
a[0,3]


2

In [73]:
a[0, :4]

array([12,  3,  3,  2])

In [74]:
a[0:3,]

array([[12,  3,  3,  2,  3,  5,  3],
       [ 2, 32,  4,  2,  7,  9,  3]])

In [75]:
a[:,1]

array([ 3, 32])

In [76]:
#Start index: end index: stepsize index
a[0, 1:-1:2]

array([3, 2, 5])

In [77]:
a[0,1]=20
print(a)

[[12 20  3  2  3  5  3]
 [ 2 32  4  2  7  9  3]]


In [78]:
a[:,1]= 5 
print(a)

[[12  5  3  2  3  5  3]
 [ 2  5  4  2  7  9  3]]


In [83]:
a[:,1]= [1,2]
print(a)


[[12  1  3  2  3  5  3]
 [ 2  2  4  2  7  9  3]]


In [81]:
print(a)

[[12  5  3  2  3  5  3]
 [ 2  5  4  2  7  9  3]]


In [89]:
b=np.array([[[0, 1, 2, 3],
...                            [4, 5, 6, 7]],
...
...                           [[0, 1, 2, 3],
...                            [4, 5, 6, 7]],
...
...                           [[0 ,1 ,2, 3],
...                            [4, 5, 6, 7]]])
print(b)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [91]:
print(b[0,1,2])

6


In [92]:
print(b[:,1,:])

[[4 5 6 7]
 [4 5 6 7]
 [4 5 6 7]]


In [8]:
#Replace

b[:,0,:] = [[9,9],[8,8],[8,2]]

NameError: name 'b' is not defined