# initializing different Types of Array

In [2]:
import numpy as np

In [11]:
#All Zero's Metrix 
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [25]:
a = np.array( [[ 1, 2, 3], 
                 [ 4, 2, 5]] ) 
print(a)

[[1 2 3]
 [4 2 5]]


In [15]:
#All 1 metrix
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.ones((2,3,4), dtype='int32')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [19]:
#Any other number 
#it takes 2 parameters

np.full((2,3),22)

array([[22, 22, 22],
       [22, 22, 22]])

In [27]:
#reuse the declared array 
np.full_like(a,2)

array([[2, 2, 2],
       [2, 2, 2]])

In [34]:
#Random decimal Numbers 
np.random.rand(4,2,2)

array([[[0.47621486, 0.44356411],
        [0.69778633, 0.08531357]],

       [[0.08515664, 0.00743354],
        [0.67791505, 0.33744765]],

       [[0.26604837, 0.16362853],
        [0.91232949, 0.58386445]],

       [[0.22901901, 0.67802629],
        [0.60378091, 0.47872181]]])

In [35]:
np.random.random_sample(a.shape)

array([[0.73111343, 0.9418969 , 0.78114124],
       [0.40260939, 0.03454793, 0.66490341]])

In [36]:
#Random integers
np.random.randint (7, size=(2,3))

array([[4, 4, 5],
       [4, 6, 3]])

In [37]:
#Identity Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
#repeat arrays
arr=np.array([[2,3,4,5]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[2 3 4 5]
 [2 3 4 5]
 [2 3 4 5]]


In [55]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1]= 9
print(z)
output [1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Be Careful when copy array

In [59]:
a= np.array([2,4,6,7,2])
b= a.copy()
b[0] = 100
print(a)

[2 4 6 7 2]
